# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - virittamotak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://virittamo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4719fffcf65b41a49b014156e5d7d7ef }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7b3a2ed2afc142ad86620ba545c4871b }}

    - run: |
        docker build . -t virittamo.azurecr.io/tyoaikakirjaus:${{ github.sha }}
        docker push virittamo.azurecr.io/tyoaikakirjaus:${{ github.sha }}
   
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'virittamotak'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9f4b3a12926041e78fbb8a3857de189e }}
        images: 'virittamo.azurecr.io/tyoaikakirjaus:${{ github.sha }}'
